#server:
#  port: 9090
# 数据源配置
spring:
  datasource:
    first:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.103.155.55:3306/jinshipark-yhq?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
      username: root
      password: Luan123456


    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.103.155.55:3306/jinshipark-adaepay?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
      username: root
      password: Luan123456


  jmx:
    enabled: false

